name: appsyncmasterclass
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: us-east-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool
mappingTemplatesLocation: mapping-templates
mappingTemplates:
  # - type: Subscription
  #   field: onNotified
  #   dataSource: none

  # - type: Query
  #   field: getAnalyticsConfig
  #   dataSource: none

  - type: Query
    field: getMyProfile
    dataSource: usersTable

  - type: Query
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFunction
    request: false
    response: false

  - type: Query
    field: getTweets
    dataSource: tweetsTable

  - type: Query
    field: getMyTimeline
    dataSource: timelinesTable

  - type: Mutation
    field: editMyProfile
    dataSource: usersTable

  - type: Mutation
    field: tweet
    dataSource: tweetFunction
    request: false
    response: false

  - type: Mutation
    field: like
    dataSource: likeMutation

  # NESTED FIELDS
  - type: Tweet
    field: profile
    dataSource: usersTable
    request: Tweet.profile.request.vtl
    response: Tweet.profile.response.vtl
    # caching:
    #   keys:
    #     - $context.identity.username
    #     - $context.source.creator
    #   ttl: 300

  - type: Tweet
    field: liked
    dataSource: likesTable

  - type: TimelinePage
    field: tweets
    dataSource: tweetsTable
    request: TimelinePage.tweets.request.vtl
    response: TimelinePage.tweets.response.vtl

dataSources:
  - type: NONE
    name: none

  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable

  - type: AMAZON_DYNAMODB
    name: tweetsTable
    config:
      tableName: !Ref TweetsTable

  - type: AMAZON_DYNAMODB
    name: timelinesTable
    config:
      tableName: !Ref TimelinesTable

  - type: AMAZON_DYNAMODB
    name: likesTable
    config:
      tableName: !Ref LikesTable

  - type: AMAZON_DYNAMODB
    name: likeMutation
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: !GetAtt LikesTable.Arn
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt TweetsTable.Arn

  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrl

  - type: AWS_LAMBDA
    name: tweetFunction
    config:
      functionName: tweet

substitutions:
  TweetsTable: !Ref TweetsTable
  LikesTable: !Ref LikesTable
  UsersTable: !Ref UsersTable
  # RelationshipsTable: !Ref RelationshipsTable
  # FirehoseStreamName: !Ref FirehoseStream
  # IdentityPoolId: !Ref IdentityPool